package com.crawljax.plugins.aji.executiontracer;

public enum FixClasses {
	NUMBER_SUFFIX_MOD,
	NODE_REINSERTION,
	EARLY_NODE_INSERTION,
	NEAR_MATCH_DL,
	NEAR_MATCH_TREE,
	SAME_PREFIX_MOD,
	TAG_NAME_MOD,
	VARIABLE_INDEX_MOD,
	NUMBER_LITERAL_INDEX_MOD,
	NEAR_TAG_MATCH
};